import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGES_LIST: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  English: {
    home: 'Home',
    categories: 'Categories',
    orders: 'Orders',
    membership: 'Membership',
    profile: 'Profile',
    daily_needs: 'Daily Needs',
    services: 'Services',
    products: 'Products',
    food: 'Food',
    stay: 'Stay',
    travel: 'Travel',
    jobs: 'Jobs',
    all: 'All',
    filter: 'Filter',
    items: 'items',
    add: '+ ADD',
    fruits_vegetables: 'Fruits & Vegetables',
    grocery_staples: 'Grocery & Staples',
    fresh_daily_needs_groceries: 'FRESH DAILY NEEDS & GROCERIES',
    my_orders: 'My Orders',
    my_bookings: 'My Bookings',
    membership_card: 'Membership Card',
    my_profile: 'My Profile',
    wallet_balance: 'Wallet Balance',
    app_preferences: 'App Preferences',
    language: 'Language',
    location: 'Location',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    logout: 'Logout',
    search_placeholder: 'Search products, food, services & more...',
    popular_near_you: 'Popular Near You',
    continue_browsing: 'Continue Browsing',
    picked_for_you: 'Picked for you',
    view_all: 'View All →',
    explore_all: 'Explore All →',
    buy_now: 'Buy Now',
    book_now: 'Book Now',
    book_service: 'Book Service',
    deliver_to: 'DELIVER TO',
    select_language: 'Select Language',
    choose_language_desc: 'Choose your preferred interface language.',
    connect_app: 'CONNECT APP',
    sign_in: 'Sign In',
    sign_in_register: 'Sign In / Register',
    cart: 'Cart',
    my_cart: 'My Cart',
    clear_all: 'Clear All',
    your_cart_is_empty: 'Your Cart is Empty',
    start_shopping_now: 'Start Shopping Now →',
    items_total: 'Items Total',
    delivery_fee: 'Delivery Fee',
    free: 'FREE',
    grand_total: 'Grand Total',
    proceed_to_checkout: 'Proceed to Checkout',
    checkout: 'Checkout',
    pay_and_place_order: 'Pay & Place Order',
    delivery_address: 'Delivery Address',
    change_address: 'Change Address',
    add_new_address: '+ Add New Address',
    order_summary: 'Order Summary',
    payment_method: 'Payment Method',
    cash_on_delivery: 'Cash on Delivery',
    online_payment: 'Online Payment (Razorpay)',
    wishlist: 'Wishlist',
    help_support: 'Help & Customer Support',
    app_theme_settings: 'App Theme Settings',
    privacy_security: 'Privacy & Security',
    saved_addresses: 'Saved Addresses',
    payment_methods: 'Payment Methods',
    edit_profile: 'Edit Profile',
    notifications: 'Notifications',
    product_details: 'Product Details',
    quantity: 'Quantity:',
    product_overview: 'Product Overview',
    highlights_features: 'Highlights & Features',
    specifications: 'Specifications',
    seller_fulfillment: 'Seller & Fulfillment',
    warranty_support: 'Warranty & Support',
    add_to_cart: 'Add to Cart',
    in_cart: 'In Cart',
    order_now: 'Order Now',
    apply_now: 'Apply Now',
    rent_now: 'Rent Now',
    reserve_stay: 'Reserve / Book Stay',
    book_ticket: 'Book Ticket',
    free_delivery_members: 'Free delivery available for Connect Members',
    verified_partner: 'Verified Partner',
    verified_vendor: 'Verified Vendor',
    authorized_seller: 'Authorized Seller',
    condition: 'Condition',
    brand_new: 'Brand New',
    information_unavailable: 'Information unavailable',
    genuine_brand_product: 'Genuine brand product with full seller warranty coverage.',
    track_live: 'Track Live',
    view_details: 'View Details',
    reorder: 'Reorder',
    cancel_order: 'Cancel Order',
    download_invoice: 'Download Invoice',
    tracking_unavailable: 'Tracking Unavailable',
    all_status: 'All Status',
    active: 'Active',
    delivered_completed: 'Delivered / Completed',
    bookings: 'Bookings',
    total_orders: 'total orders',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    email_address: 'Email Address',
    date_of_birth: 'Date of Birth',
    save_changes: 'Save Changes',
    stay_details: 'Stay Details',
    check_in: 'Check-in',
    check_out: 'Check-out',
    guests_and_rooms: 'Guests & Rooms',
  },
  Hindi: {
    home: 'होम',
    categories: 'श्रेणियां',
    orders: 'ऑर्डर',
    membership: 'सदस्यता',
    profile: 'प्रोफाइल',
    daily_needs: 'दैनिक जरूरतें',
    services: 'सेवाएं',
    products: 'उत्पाद',
    food: 'भोजन',
    stay: 'स्टे',
    travel: 'यात्रा',
    jobs: 'नौकरियां',
    all: 'सभी',
    filter: 'फ़िल्टर',
    items: 'आइटम',
    add: '+ जोड़ें',
    fruits_vegetables: 'फल और सब्जियां',
    grocery_staples: 'किराना और खाद्यान्न',
    fresh_daily_needs_groceries: 'ताज़ा दैनिक ज़रूरतें और किराना',
    my_orders: 'मेरे ऑर्डर',
    my_bookings: 'मेरी बुकिंग',
    membership_card: 'सदस्यता कार्ड',
    my_profile: 'मेरी प्रोफाइल',
    wallet_balance: 'वॉलेट बैलेंस',
    app_preferences: 'ऐप प्राथमिकताएं',
    language: 'भाषा',
    location: 'स्थान',
    light: 'लाइट',
    dark: 'डार्क',
    system: 'सिस्टम',
    logout: 'लॉगआउट',
    search_placeholder: 'उत्पाद, भोजन, सेवाएं और अधिक खोजें...',
    popular_near_you: 'आपके पास लोकप्रिय',
    continue_browsing: 'ब्राउज़िंग जारी रखें',
    picked_for_you: 'आपके लिए चुने गए',
    view_all: 'सभी देखें →',
    explore_all: 'एक्सप्लोर करें →',
    buy_now: 'अभी खरीदें',
    book_now: 'अभी बुक करें',
    book_service: 'सेवा बुक करें',
    deliver_to: 'डिलिवरी का पता',
    select_language: 'भाषा चुनें',
    choose_language_desc: 'अपनी पसंदीदा भाषा चुनें।',
    connect_app: 'कनेक्ट ऐप',
    sign_in: 'साइन इन',
    sign_in_register: 'साइन इन / रजिस्टर',
    cart: 'कार्ट',
    my_cart: 'मेरी कार्ट',
    clear_all: 'सभी हटाएं',
    your_cart_is_empty: 'आपकी कार्ट खाली है',
    start_shopping_now: 'अभी खरीदारी शुरू करें →',
    items_total: 'आइटम कुल',
    delivery_fee: 'डिलीवरी शुल्क',
    free: 'मुफ्त',
    grand_total: 'कुल योग',
    proceed_to_checkout: 'चेकआउट पर आगे बढ़ें',
    checkout: 'चेकआउट',
    pay_and_place_order: 'भुगतान करें और ऑर्डर दें',
    delivery_address: 'डिलीवरी का पता',
    change_address: 'पता बदलें',
    add_new_address: '+ नया पता जोड़ें',
    order_summary: 'ऑर्डर का सारांश',
    payment_method: 'भुगतान का तरीका',
    cash_on_delivery: 'कैश ऑन डिलीवरी',
    online_payment: 'ऑनलाइन भुगतान (रेज़रपे)',
    wishlist: 'विशलिस्ट',
    help_support: 'सहायता और ग्राहक सहायता',
    app_theme_settings: 'ऐप थीम सेटिंग्स',
    privacy_security: 'गोपनीयता और सुरक्षा',
    saved_addresses: 'सहेजे गए पते',
    payment_methods: 'भुगतान के तरीके',
    edit_profile: 'प्रोफाइल संपादित करें',
    notifications: 'सूचनाएं',
    product_details: 'उत्पाद विवरण',
    quantity: 'मात्रा:',
    product_overview: 'उत्पाद अवलोकन',
    highlights_features: 'प्रमुख विशेषताएं',
    specifications: 'विशिष्टताएं',
    seller_fulfillment: 'विक्रेता और पूर्ति',
    warranty_support: 'वारंटी और सहायता',
    add_to_cart: 'कार्ट में जोड़ें',
    in_cart: 'कार्ट में है',
    order_now: 'अभी ऑर्डर करें',
    apply_now: 'अभी आवेदन करें',
    rent_now: 'किराए पर लें',
    reserve_stay: 'स्टे बुक करें',
    book_ticket: 'टिकट बुक करें',
    free_delivery_members: 'कनेक्ट सदस्यों के लिए मुफ्त डिलीवरी',
    verified_partner: 'सत्यापित भागीदार',
    verified_vendor: 'सत्यापित विक्रेता',
    authorized_seller: 'अधिकृत विक्रेता',
    condition: 'स्थिति',
    brand_new: 'बिल्कुल नया',
    information_unavailable: 'जानकारी उपलब्ध नहीं',
    genuine_brand_product: 'पूर्ण विक्रेता वारंटी के साथ असली ब्रांड उत्पाद।',
    track_live: 'लाइव ट्रैक करें',
    view_details: 'विवरण देखें',
    reorder: 'पुनः ऑर्डर करें',
    cancel_order: 'ऑर्डर रद्द करें',
    download_invoice: 'चालान डाउनलोड करें',
    tracking_unavailable: 'ट्रैकिंग उपलब्ध नहीं है',
    all_status: 'सभी स्थिति',
    active: 'सक्रिय',
    delivered_completed: 'डिलीवर हुआ / पूरा',
    bookings: 'बुकिंग',
    total_orders: 'कुल ऑर्डर',
    full_name: 'पूरा नाम',
    phone_number: 'फोन नंबर',
    email_address: 'ईमेल पता',
    date_of_birth: 'जन्म तिथि',
    save_changes: 'बदलाव सहेजें',
    stay_details: 'स्टे विवरण',
    check_in: 'चेक-इन',
    check_out: 'चेक-आउट',
    guests_and_rooms: 'अतिथि और कमरे',
  },
  Kannada: {
    home: 'ಹೋಮ್',
    categories: 'ವರ್ಗಗಳು',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    membership: 'ಸದಸ್ಯತ್ವ',
    profile: 'ಪ್ರೊಫೈಲ್',
    daily_needs: 'ದೈನಂದಿನ ಅಗತ್ಯಗಳು',
    services: 'ಸೇವೆಗಳು',
    products: 'ಉತ್ಪನ್ನಗಳು',
    food: 'ಆಹಾರ',
    stay: 'ಸ್ಟೇ',
    travel: 'ಪ್ರಯಾಣ',
    jobs: 'ಉದ್ಯೋಗಗಳು',
    all: 'ಎಲ್ಲವೂ',
    filter: 'ಫಿಲ್ಟರ್',
    items: 'ಐಟಂಗಳು',
    add: '+ ಸೇರಿಸಿ',
    fruits_vegetables: 'ಹಣ್ಣುಗಳು & ತರಕಾರಿಗಳು',
    grocery_staples: 'ಕಿರಾಣಿ & ಧಾನ್ಯಗಳು',
    fresh_daily_needs_groceries: 'ತಾಜಾ ದೈನಂದಿನ ಅಗತ್ಯಗಳು & ಕಿರಾಣಿ',
    my_orders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    my_bookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    membership_card: 'ಸದಸ್ಯತ್ವ ಕಾರ್ಡ್',
    my_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    wallet_balance: 'ವ್ಯಾಲೆಟ್ ಬಾಕಿ',
    app_preferences: 'ಆ್ಯಪ್ ಆಯ್ಕೆಗಳು',
    language: 'ಭಾಷೆ',
    location: 'ಸ್ಥಳ',
    light: 'ಲೈಟ್',
    dark: 'ಡಾರ್ಕ್',
    system: 'ಸಿಸ್ಟಮ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    search_placeholder: 'ಉತ್ಪನ್ನಗಳು, ಆಹಾರ, ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
    popular_near_you: 'ನಿಮ್ಮ ಹತ್ತಿರ ಜನಪ್ರಿಯ',
    continue_browsing: 'ಬ್ರೌಸಿಂಗ್ ಮುಂದುವರಿಸಿ',
    picked_for_you: 'ನಿಮಗಾಗಿ ಆಯ್ಕೆ ಮಾಡಿದ್ದು',
    view_all: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ →',
    explore_all: 'ಎಕ್ಸ್‌ಪ್ಲೋರ್ ಮಾಡಿ →',
    buy_now: 'ಈಗಲೇ ಖರೀದಿಸಿ',
    book_now: 'ಈಗಲೇ ಬುಕ್ ಮಾಡಿ',
    book_service: 'ಸೇವೆ ಬುಕ್ ಮಾಡಿ',
    deliver_to: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    choose_language_desc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    connect_app: 'ಕನೆಕ್ಟ್ ಆ್ಯಪ್',
    sign_in: 'ಸೈನ್ ಇನ್',
    sign_in_register: 'ಸೈನ್ ಇನ್ / ನೋಂದಾಯಿಸಿ',
    cart: 'ಕಾರ್ಟ್',
    my_cart: 'ನನ್ನ ಕಾರ್ಟ್',
    clear_all: 'ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ',
    your_cart_is_empty: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿ ಇದೆ',
    start_shopping_now: 'ಈಗಲೇ ಶಾಪಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ →',
    items_total: 'ಐಟಂ ಒಟ್ಟು',
    delivery_fee: 'ಡೆಲಿವರಿ ಶುಲ್ಕ',
    free: 'ಉಚಿತ',
    grand_total: 'ಒಟ್ಟು ಮೊತ್ತ',
    proceed_to_checkout: 'ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ',
    checkout: 'ಚೆಕ್‌ಔಟ್',
    pay_and_place_order: 'ಪಾವತಿಸಿ ಮತ್ತು ಆರ್ಡರ್ ಮಾಡಿ',
    delivery_address: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    change_address: 'ವಿಳಾಸ ಬದಲಾಯಿಸಿ',
    add_new_address: '+ ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ',
    order_summary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
    payment_method: 'ಪಾವತಿ ವಿಧಾನ',
    cash_on_delivery: 'ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ',
    online_payment: 'ಆನ್‌ಲೈನ್ ಪಾವತಿ',
    wishlist: 'ವಿಶ್‌ಲಿಸ್ಟ್',
    help_support: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    app_theme_settings: 'ಆ್ಯಪ್ ಥೀಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    privacy_security: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
    saved_addresses: 'ಉಳಿಸಿದ ವಿಳಾಸಗಳು',
    payment_methods: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
    notifications: 'ಸೂಚನೆಗಳು',
    product_details: 'ಉತ್ಪನ್ನ ವಿವರಗಳು',
    quantity: 'ಪ್ರಮಾಣ:',
    product_overview: 'ಉತ್ಪನ್ನದ ವಿವರಣೆ',
    highlights_features: 'ಪ್ರಮುಖ ಮುಖ್ಯಾಂಶಗಳು',
    specifications: 'ಸ್ಪೆಸಿಫಿಕೇಶನ್‌ಗಳು',
    seller_fulfillment: 'ಮಾರಾಟಗಾರ ಮತ್ತು ಪೂರೈಕೆ',
    warranty_support: 'ವಾರಂಟಿ ಮತ್ತು ಬೆಂಬಲ',
    add_to_cart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    in_cart: 'ಕಾರ್ಟ್‌ನಲ್ಲಿದೆ',
    order_now: 'ಈಗಲೇ ಆರ್ಡರ್ ಮಾಡಿ',
    apply_now: 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    rent_now: 'ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ',
    reserve_stay: 'ಸ್ಟೇ ಬುಕ್ ಮಾಡಿ',
    book_ticket: 'ಟಿಕೆಟ್ ಬುಕ್ ಮಾಡಿ',
    free_delivery_members: 'ಕನೆಕ್ಟ್ ಸದಸ್ಯರಿಗೆ ಉಚಿತ ಡೆಲಿವರಿ',
    verified_partner: 'ಪರಿಶೀಲಿಸಿದ ಪಾಲುದಾರ',
    verified_vendor: 'ಪರಿಶೀಲಿಸಿದ ಮಾರಾಟಗಾರ',
    authorized_seller: 'ಅಧಿಕೃತ ಮಾರಾಟಗಾರ',
    condition: 'ಸ್ಥಿತಿ',
    brand_new: 'ಬ್ರ್ಯಾಂಡ್ ನ್ಯೂ',
    information_unavailable: 'ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ',
    genuine_brand_product: 'ಪೂರ್ಣ ಮಾರಾಟಗಾರರ ವಾರಂಟಿಯೊಂದಿಗೆ ಅಸಲಿ ಬ್ರ್ಯಾಂಡ್ ಉತ್ಪನ್ನ.',
    track_live: 'ಲೈವ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    view_details: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    reorder: 'ಮರುಆರ್ಡರ್ ಮಾಡಿ',
    cancel_order: 'ಆರ್ಡರ್ ರದ್ದುಮಾಡಿ',
    download_invoice: 'ಇನ್‌ವಾಯ್ಸ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    tracking_unavailable: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಲಭ್ಯವಿಲ್ಲ',
    all_status: 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
    active: 'ಸಕ್ರಿಯ',
    delivered_completed: 'ಡೆಲಿವರಿ ಮಾಡಲಾಗಿದೆ',
    bookings: 'ಬುಕಿಂಗ್‌ಗಳು',
    total_orders: 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    phone_number: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    email_address: 'ಇಮೇಲ್ ವಿಳಾಸ',
    date_of_birth: 'ಜನ್ಮ ದಿನಾಂಕ',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    stay_details: 'ಸ್ಟೇ ವಿವರಗಳು',
    check_in: 'ಚೆಕ್-ಇನ್',
    check_out: 'ಚೆಕ್-ಔಟ್',
    guests_and_rooms: 'ಅತಿಥಿಗಳು & ಕೊಠಡಿಗಳು',
  },
  Tamil: {
    home: 'முகப்பு',
    categories: 'பிரிவுகள்',
    orders: 'ஆர்டர்கள்',
    membership: 'உறுப்பினர்',
    profile: 'சுயவிவரம்',
    daily_needs: 'தினசரி தேவைகள்',
    services: 'சேவைகள்',
    products: 'தயாரிப்புகள்',
    food: 'உணவு',
    stay: 'தங்குமிடம்',
    travel: 'பயணம்',
    jobs: 'வேலைகள்',
    all: 'அனைத்தும்',
    filter: 'வடிகட்டி',
    items: 'பொருட்கள்',
    add: '+ சேர்',
    fruits_vegetables: 'பழங்கள் & காய்கறிகள்',
    grocery_staples: 'மளிகை & தானியங்கள்',
    fresh_daily_needs_groceries: 'புதிய தினசரி தேவைகள் & மளிகை',
    my_orders: 'என் ஆர்டர்கள்',
    my_bookings: 'என் முன்பதிவுகள்',
    membership_card: 'உறுப்பினர் அட்டை',
    my_profile: 'என் சுயவிவரம்',
    wallet_balance: 'வாலட் இருப்பு',
    app_preferences: 'செயலி விருப்பங்கள்',
    language: 'மொழி',
    location: 'இருப்பிடம்',
    light: 'லைட்',
    dark: 'டார்க்',
    system: 'சிஸ்டம்',
    logout: 'வெளியேறு',
    search_placeholder: 'தயாரிப்புகள், உணவு, சேவைகள் தேடவும்...',
    popular_near_you: 'உங்கள் அருகில் பிரபலம்',
    continue_browsing: 'தொடர்ந்து உலாவுக',
    picked_for_you: 'உங்களுக்காக தேர்ந்தெடுக்கப்பட்டவை',
    view_all: 'அனைத்தும் காண்க →',
    explore_all: 'அனைத்தும் ஆராய்க →',
    buy_now: 'இப்போதே வாங்கு',
    book_now: 'இப்போதே பதிவு செய்',
    book_service: 'சேவை முன்பதிவு',
    deliver_to: 'டெலிவரி முகவரி',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    choose_language_desc: 'உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    connect_app: 'கனெக்ட் செயலி',
    sign_in: 'லாக் இன்',
    sign_in_register: 'லாக் இன் / பதிவு செய்க',
    cart: 'கார்ட்',
    my_cart: 'என் கார்ட்',
    clear_all: 'அனைத்தும் நீக்கு',
    your_cart_is_empty: 'உங்கள் கார்ட் காலியாக உள்ளது',
    start_shopping_now: 'இப்போதே ஷாப்பிங் தொடங்குங்கள் →',
    items_total: 'பொருட்களின் மொத்தம்',
    delivery_fee: 'டெலிவரி கட்டணம்',
    free: 'இலவசம்',
    grand_total: 'மொத்த தொகை',
    proceed_to_checkout: 'செக்அவுட்டிற்கு செல்லவும்',
    checkout: 'செக்அவுட்',
    pay_and_place_order: 'பணம் செலுத்தி ஆர்டர் செய்',
    delivery_address: 'டெலிவரி முகவரி',
    change_address: 'முகவரி மாற்று',
    add_new_address: '+ புதிய முகவரி சேர்',
    order_summary: 'ஆர்டர் சுருக்கம்',
    payment_method: 'பணம் செலுத்தும் முறை',
    cash_on_delivery: 'கேஷ் ஆன் டெலிவரி',
    online_payment: 'ஆன்லைன் பணம் செலுத்துதல்',
    wishlist: 'விருப்பப்பட்டியல்',
    help_support: 'உதவி & ஆதரவு',
    app_theme_settings: 'தீம் அமைப்புகள்',
    privacy_security: 'தனியுரிமை & பாதுகாப்பு',
    saved_addresses: 'சேமிக்கப்பட்ட முகவரிகள்',
    payment_methods: 'பணம் செலுத்தும் முறைகள்',
    edit_profile: 'சுயவிவரம் திருத்து',
    notifications: 'அறிவிப்புகள்',
    product_details: 'தயாரிப்பு விவரங்கள்',
    quantity: 'அளவு:',
    product_overview: 'தயாரிப்பு மேலோட்டம்',
    highlights_features: 'சிறப்பம்சங்கள் & அம்சங்கள்',
    specifications: 'விவரக்குறிப்புகள்',
    seller_fulfillment: 'விற்பனையாளர் & நிறைவேற்றம்',
    warranty_support: 'உத்திரவாதம் & ஆதரவு',
    add_to_cart: 'கார்ட்டில் சேர்',
    in_cart: 'கார்ட்டில் உள்ளது',
    order_now: 'இப்போதே ஆர்டர் செய்',
    apply_now: 'இப்போதே விண்ணப்பிக்கவும்',
    rent_now: 'வாடகைக்கு எடுக்கவும்',
    reserve_stay: 'தங்குமிடம் பதிவு செய்',
    book_ticket: 'டிக்கெட் பதிவு செய்',
    free_delivery_members: 'கனெக்ட் உறுப்பினர்களுக்கு இலவச டெலிவரி',
    verified_partner: 'சரிபார்க்கப்பட்ட கூட்டாளர்',
    verified_vendor: 'சரிபார்க்கப்பட்ட விற்பனையாளர்',
    authorized_seller: 'அங்கீகரிக்கப்பட்ட விற்பனையாளர்',
    condition: 'நிலை',
    brand_new: 'புதியது',
    information_unavailable: 'தகவல் கிடைக்கவில்லை',
    genuine_brand_product: 'முழு விற்பனையாளர் உத்திரவாதத்துடன் அசல் பிராண்ட் தயாரிப்பு.',
    track_live: 'லைவ் டிராக் செய்',
    view_details: 'விவரங்களை காண்க',
    reorder: 'மீண்டும் ஆர்டர் செய்',
    cancel_order: 'ஆர்டர் ரத்து செய்',
    download_invoice: 'ரசீது பதிவிறக்கம் செய்',
    tracking_unavailable: 'டிராக்கிங் கிடைக்கவில்லை',
    all_status: 'அனைத்து நிலை',
    active: 'செயலில்',
    delivered_completed: 'டெலிவரி செய்யப்பட்டது',
    bookings: 'முன்பதிவுகள்',
    total_orders: 'மொத்த ஆர்டர்கள்',
    full_name: 'முழு பெயர்',
    phone_number: 'போன் எண்',
    email_address: 'மின்னஞ்சல் முகவரி',
    date_of_birth: 'பிறந்த தேதி',
    save_changes: 'மாற்றங்களைச் சேமி',
    stay_details: 'தங்குமிடம் விவரங்கள்',
    check_in: 'செக்-இன்',
    check_out: 'செக்-அவுட்',
    guests_and_rooms: 'விருந்தினர்கள் & அறைகள்',
  },
  Telugu: {
    home: 'హోమ్',
    categories: 'వర్గాలు',
    orders: 'ఆర్డర్‌లు',
    membership: 'సభ్యత్వం',
    profile: 'ప్రొఫైల్',
    daily_needs: 'దినసరి అవసరాలు',
    services: 'సేవలు',
    products: 'ఉత్పత్తులు',
    food: 'ఆహారం',
    stay: 'స్టే',
    travel: 'ప్రయాణం',
    jobs: 'ఉద్యోగాలు',
    all: 'అన్నీ',
    filter: 'ఫిల్టర్',
    items: 'ఐటెమ్‌లు',
    add: '+ జోడించు',
    fruits_vegetables: 'పండ్లు & కూరగాయలు',
    grocery_staples: 'సరుకులు & ధాన్యాలు',
    fresh_daily_needs_groceries: 'తాజా దినసరి అవసరాలు & సరుకులు',
    my_orders: 'నా ఆర్డర్‌లు',
    my_bookings: 'నా బుకింగ్‌లు',
    membership_card: 'సభ్యత్వ కార్డు',
    my_profile: 'నా ప్రొఫైల్',
    wallet_balance: 'వాలెట్ నిల్వ',
    app_preferences: 'యాప్ ప్రాధాన్యతలు',
    language: 'భాష',
    location: 'ప్రాంతం',
    light: 'లైట్',
    dark: 'డార్క్',
    system: 'సిస్టమ్',
    logout: 'లాగౌట్',
    search_placeholder: 'ఉత్పత్తులు, ఆహారం, సేవలను శోధించండి...',
    popular_near_you: 'మీ దగ్గర ప్రాచుర్యం',
    continue_browsing: 'బ్రౌజింగ్ కొనసాగించండి',
    picked_for_you: 'మీ కోసం ఎంచుకోబడినవి',
    view_all: 'అన్నీ చూడండి →',
    explore_all: 'అన్నీ ఎక్స్‌ప్లోర్ చేయండి →',
    buy_now: 'ఇప్పుడే కొనండి',
    book_now: 'ఇప్పుడే బుక్ చేయండి',
    book_service: 'సేవ బుక్ చేయండి',
    deliver_to: 'డెలివరీ చిరునామా',
    select_language: 'భాషను ఎంచుకోండి',
    choose_language_desc: 'మీకు ఇష్టమైన భాషను ఎంచుకోండి.',
    connect_app: 'కనెక్ట్ యాప్',
    sign_in: 'సైన్ ఇన్',
    sign_in_register: 'సైన్ ఇన్ / రిజిస్టర్',
    cart: 'కార్ట్',
    my_cart: 'నా కార్ట్',
    clear_all: 'అన్నీ తొలగించు',
    your_cart_is_empty: 'మీ కార్ట్ ఖాళీగా ఉంది',
    start_shopping_now: 'ఇప్పుడే షాపింగ్ ప్రారంభించండి →',
    items_total: 'ఐటెమ్‌ల మొత్తం',
    delivery_fee: 'డెలివరీ రుసుము',
    free: 'ఉచితం',
    grand_total: 'మొత్తం విలువా',
    proceed_to_checkout: 'చెక్‌అవుట్‌కు వెళ్లండి',
    checkout: 'చెక్‌అవుట్',
    pay_and_place_order: 'చెల్లించి ఆర్డర్ చేయండి',
    delivery_address: 'డెలివరీ చిరునామా',
    change_address: 'చిరునామా మార్చండి',
    add_new_address: '+ కొత్త చిరునామా జోడించు',
    order_summary: 'ఆర్డర్ సారాంశం',
    payment_method: 'చెల్లింపు పద్ధతి',
    cash_on_delivery: 'క్యాష్ ఆన్ డెలివరీ',
    online_payment: 'ఆన్‌లైన్ చెల్లింపు',
    wishlist: 'విష్‌లిస్ట్',
    help_support: 'సహాయం & మద్దతు',
    app_theme_settings: 'యాప్ థీమ్ సెట్టింగ్‌లు',
    privacy_security: 'గోప్యత & భద్రత',
    saved_addresses: 'సేవ్ చేసిన చిరునామాలు',
    payment_methods: 'చెల్లింపు పద్ధతులు',
    edit_profile: 'ప్రొఫైల్ ఎడిట్',
    notifications: 'నోటిఫికేషన్‌లు',
    product_details: 'ఉత్పత్తి వివరాలు',
    quantity: 'పరిమాణం:',
    product_overview: 'ఉత్పత్తి అవలోకనం',
    highlights_features: 'ముఖ్యాంశాలు & ఫీచర్లు',
    specifications: 'నిర్దేశాలు',
    seller_fulfillment: 'విక్రేత & నెరవేర్పు',
    warranty_support: 'వారంటీ & మద్దతు',
    add_to_cart: 'కార్ట్‌కు జోడించు',
    in_cart: 'కార్ట్‌లో ఉంది',
    order_now: 'ఇప్పుడే ఆర్డర్ చేయండి',
    apply_now: 'ఇప్పుడే దరఖాస్తు చేయండి',
    rent_now: 'అద్దెకు తీసుకోండి',
    reserve_stay: 'స్టే బుక్ చేయండి',
    book_ticket: 'టికెట్ బుక్ చేయండి',
    free_delivery_members: 'కనెక్ట్ సభ్యులకు ఉచిత డెలివరీ',
    verified_partner: 'తనిఖీ చేసిన భాగస్వామి',
    verified_vendor: 'తనిఖీ చేసిన విక్రేత',
    authorized_seller: 'అధీకృత విక్రేత',
    condition: 'పరిస్థితి',
    brand_new: 'కొత్తది',
    information_unavailable: 'సమాచారం అందుబాటులో లేదు',
    genuine_brand_product: 'పూర్తి విక్రేత వారంటీతో అసలైన బ్రాండ్ ఉత్పత్తి.',
    track_live: 'లైవ్ ట్రాక్ చేయండి',
    view_details: 'వివరాలు చూడండి',
    reorder: 'మళ్లీ ఆర్డర్ చేయండి',
    cancel_order: 'ఆర్డర్ రద్దు చేయండి',
    download_invoice: 'ఇన్‌వాయిస్ డౌన్‌లోడ్ చేయండి',
    tracking_unavailable: 'ట్రాకింగ్ అందుబాటులో లేదు',
    all_status: 'అన్ని హోదా',
    active: 'సక్రియం',
    delivered_completed: 'డెలివరీ పూర్తయింది',
    bookings: 'బుకింగ్‌లు',
    total_orders: 'మొత్తం ఆర్డర్‌లు',
    full_name: 'పూర్తి పేరు',
    phone_number: 'ఫోన్ నంబర్',
    email_address: 'ఈమెయిల్ చిరునామా',
    date_of_birth: 'పుట్టిన తేదీ',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    stay_details: 'స్టే వివరాలు',
    check_in: 'చెక్-ఇన్',
    check_out: 'చెక్-అవుట్',
    guests_and_rooms: 'అతిథులు & గదులు',
  },
  Malayalam: {
    home: 'ഹോം',
    categories: 'വിഭാഗങ്ങൾ',
    orders: 'ഓർഡറുകൾ',
    membership: 'അംഗത്വം',
    profile: 'പ്രൊഫൈൽ',
    daily_needs: 'ദിനചര്യ ആവശ്യങ്ങൾ',
    services: 'സേവനങ്ങൾ',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    food: 'ഭക്ഷണം',
    stay: 'സ്റ്റേ',
    travel: 'യാത്ര',
    jobs: 'ജോലികൾ',
    all: 'എല്ലാം',
    filter: 'ഫിൽട്ടർ',
    items: 'ഐറ്റങ്ങൾ',
    add: '+ ചേർക്കുക',
    fruits_vegetables: 'പഴങ്ങളും പച്ചക്കറികളും',
    grocery_staples: 'ഗ്രോസറിയും ധാന്യങ്ങളും',
    fresh_daily_needs_groceries: 'ഫ്രഷ് ദിനചര്യ ആവശ്യങ്ങൾ & ഗ്രോസറി',
    my_orders: 'എന്റെ ഓർഡറുകൾ',
    my_bookings: 'എന്റെ ബുക്കിംഗുകൾ',
    membership_card: 'അംഗത്വ കാർഡ്',
    my_profile: 'എന്റെ പ്രൊഫൈൽ',
    wallet_balance: 'വാലറ്റ് ബാലൻസ്',
    app_preferences: 'ആപ്പ് മുൻഗണനകൾ',
    language: 'ഭാഷ',
    location: 'സ്ഥലം',
    light: 'ലൈറ്റ്',
    dark: 'ഡാർക്ക്',
    system: 'സിസ്റ്റം',
    logout: 'ലോഗ്ഔട്ട്',
    search_placeholder: 'ഉൽപ്പന്നങ്ങൾ, ഭക്ഷണം, സേവനങ്ങൾ തിരയുക...',
    popular_near_you: 'നിങ്ങൾക്ക് സമീപം പ്രശസ്തമായവ',
    continue_browsing: 'ബ്രൗസിംഗ് തുടരുക',
    picked_for_you: 'നിങ്ങൾക്കായി തിരഞ്ഞെടുത്തവ',
    view_all: 'എല്ലാം കാണുക →',
    explore_all: 'എല്ലാം എക്സ്പ്ലോർ ചെയ്യുക →',
    buy_now: 'ഇപ്പോൾ വാങ്ങുക',
    book_now: 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
    book_service: 'സേവനം ബുക്ക് ചെയ്യുക',
    deliver_to: 'ഡെലിവറി വിലാസം',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    choose_language_desc: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക.',
    connect_app: 'കണക്റ്റ് ആപ്പ്',
    sign_in: 'സൈൻ ഇൻ',
    sign_in_register: 'സൈൻ ഇൻ / രജിസ്റ്റർ',
    cart: 'കാർട്ട്',
    my_cart: 'എന്റെ കാർട്ട്',
    clear_all: 'എല്ലാം നീക്കം ചെയ്യുക',
    your_cart_is_empty: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
    start_shopping_now: 'ഇപ്പോൾ ഷോപ്പിംഗ് ആരംഭിക്കുക →',
    items_total: 'ഐറ്റങ്ങളുടെ ആകെത്തുക',
    delivery_fee: 'ഡെലിവറി ഫീസ്',
    free: 'സൗജന്യം',
    grand_total: 'ആകെ തുക',
    proceed_to_checkout: 'ചെക്ക്ഔട്ടിലേക്ക് തുടരുക',
    checkout: 'ചെക്ക്ഔട്ട്',
    pay_and_place_order: 'പേ ചെയ്ത് ഓർഡർ നൽകുക',
    delivery_address: 'ഡെലിവറി വിലാസം',
    change_address: 'വിലാസം മാറ്റുക',
    add_new_address: '+ പുതിയ വിലാസം ചേർക്കുക',
    order_summary: 'ഓർഡർ ചുരുക്കം',
    payment_method: 'പേയ്‌മെന്റ് രീതി',
    cash_on_delivery: 'ക്യാഷ് ഓൺ ഡെലിവറി',
    online_payment: 'ഓൺലൈൻ പേയ്‌മെന്റ്',
    wishlist: 'വിഷ്‌ലിസ്റ്റ്',
    help_support: 'സഹായം & പിന്തുണ',
    app_theme_settings: 'തീം ക്രമീകരണങ്ങൾ',
    privacy_security: 'സ്വകാര്യത & സുരക്ഷ',
    saved_addresses: 'സേവ് ചെയ്ത വിലാസങ്ങൾ',
    payment_methods: 'പേയ്‌മെന്റ് രീതികൾ',
    edit_profile: 'പ്രൊഫൈൽ എഡിറ്റ്',
    notifications: 'അറിയിപ്പുകൾ',
    product_details: 'ഉൽപ്പന്ന വിവരങ്ങൾ',
    quantity: 'അളവ്:',
    product_overview: 'ഉൽപ്പന്ന അവലോകനം',
    highlights_features: 'ഹൈലൈറ്റുകൾ & സവിശേഷതകൾ',
    specifications: 'സവിശേഷതകൾ',
    seller_fulfillment: 'വിൽപനക്കാരനും പൂർത്തീകരണവും',
    warranty_support: 'വാറണ്ടിയും പിന്തുണയും',
    add_to_cart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    in_cart: 'കാർട്ടിലുണ്ട്',
    order_now: 'ഇപ്പോൾ ഓർഡർ ചെയ്യുക',
    apply_now: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    rent_now: 'വാടകയ്ക്ക് എടുക്കുക',
    reserve_stay: 'സ്റ്റേ ബുക്ക് ചെയ്യുക',
    book_ticket: 'ടിക്കറ്റ് ബുക്ക് ചെയ്യുക',
    free_delivery_members: 'കണക്റ്റ് അംഗങ്ങൾക്ക് സൗജന്യ ഡെലിവറി',
    verified_partner: 'വെരിഫൈഡ് പങ്കാളി',
    verified_vendor: 'വെരിഫൈഡ് വിൽപനക്കാരൻ',
    authorized_seller: 'അംഗീകൃത വിൽപനക്കാരൻ',
    condition: 'അവസ്ഥ',
    brand_new: 'പുതിയത്',
    information_unavailable: 'വിവരങ്ങൾ ലഭ്യമല്ല',
    genuine_brand_product: 'പൂർണ്ണ വിൽപനക്കാരന്റെ വാറണ്ടിയുള്ള അസൽ ബ്രാൻഡ് ഉൽപ്പന്നം.',
    track_live: 'ലൈവ് ട്രാക്ക് ചെയ്യുക',
    view_details: 'വിവരങ്ങൾ കാണുക',
    reorder: 'വീണ്ടും ഓർഡർ ചെയ്യുക',
    cancel_order: 'ഓർഡർ റദ്ദാക്കുക',
    download_invoice: 'ഇൻവോയ്സ് ഡൗൺലോഡ് ചെയ്യുക',
    tracking_unavailable: 'ട്രാക്കിംഗ് ലഭ്യമല്ല',
    all_status: 'എല്ലാ നിലയും',
    active: 'സജീവം',
    delivered_completed: 'ഡെലിവർ ചെയ്തു',
    bookings: 'ബുക്കിംഗുകൾ',
    total_orders: 'ആകെ ഓർഡറുകൾ',
    full_name: 'പൂർണ്ണ പേര്',
    phone_number: 'ഫോൺ നമ്പർ',
    email_address: 'ഇമെയിൽ വിലാസം',
    date_of_birth: 'ജനന തീയതി',
    save_changes: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    stay_details: 'സ്റ്റേ വിവരങ്ങൾ',
    check_in: 'ചെക്ക്-ഇൻ',
    check_out: 'ചെക്ക്-ഔട്ട്',
    guests_and_rooms: 'അതിഥികളും മുറികളും',
  },
  Marathi: {
    home: 'होम',
    categories: 'वर्ग',
    orders: 'ऑर्डर्स',
    membership: 'सदस्यत्व',
    profile: 'प्रोफाइल',
    daily_needs: 'दैनंदिन गरजा',
    services: 'सेवा',
    products: 'उत्पादने',
    food: 'अन्न',
    stay: 'स्टे',
    travel: 'प्रवास',
    jobs: 'नोकऱ्या',
    all: 'सर्व',
    filter: 'फिल्टर',
    items: 'आयटम',
    add: '+ जोडा',
    fruits_vegetables: 'फळे आणि भाज्या',
    grocery_staples: 'किराणा आणि धान्य',
    fresh_daily_needs_groceries: 'ताजे दैनंदिन गरजा आणि किराणा',
    my_orders: 'माझे ऑर्डर्स',
    my_bookings: 'माझ्या बुकिंग्ज',
    membership_card: 'सदस्यत्व कार्ड',
    my_profile: 'माझी प्रोफाइल',
    wallet_balance: 'वॉलेट शिल्लक',
    app_preferences: 'अ‍ॅप पसंती',
    language: 'भाषा',
    location: 'स्थान',
    light: 'लाइट',
    dark: 'डार्क',
    system: 'सिस्टम',
    logout: 'लॉगआउट',
    search_placeholder: 'उत्पादने, अन्न, सेवा शोधा...',
    popular_near_you: 'तुमच्याजवळ लोकप्रिय',
    continue_browsing: 'ब्राउझिंग सुरू ठेवा',
    picked_for_you: 'तुमच्यासाठी निवडलेले',
    view_all: 'सर्व पहा →',
    explore_all: 'सर्व एक्सप्लोर करा →',
    buy_now: 'आत्ताच खरेदी करा',
    book_now: 'आत्ताच बुक करा',
    book_service: 'सेवा बुक करा',
    deliver_to: 'डिलिव्हरी पत्ता',
    select_language: 'भाषा निवडा',
    choose_language_desc: 'तुमची पसंतीची भाषा निवडा.',
    connect_app: 'कनेक्ट अ‍ॅप',
    sign_in: 'साइन इन',
    sign_in_register: 'साइन इन / नोंदणी करा',
    cart: 'कार्ट',
    my_cart: 'माझी कार्ट',
    clear_all: 'सर्व हटवा',
    your_cart_is_empty: 'तुमची कार्ट रिकामी आहे',
    start_shopping_now: 'आत्ताच खरेदी सुरू करा →',
    items_total: 'आयटम एकूण',
    delivery_fee: 'डिलिव्हरी शुल्क',
    free: 'मोफत',
    grand_total: 'एकूण रक्कम',
    proceed_to_checkout: 'चेकआउटवर पुढे जा',
    checkout: 'चेकआउट',
    pay_and_place_order: 'पैसे द्या आणि ऑर्डर द्या',
    delivery_address: 'डिलिव्हरी पत्ता',
    change_address: 'पत्ता बदला',
    add_new_address: '+ नवीन पत्ता जोडा',
    order_summary: 'ऑर्डर सारांश',
    payment_method: 'पैसे भरण्याची पद्धत',
    cash_on_delivery: 'कॅश ऑन डिलिव्हरी',
    online_payment: 'ऑनलाइन पेमेंट',
    wishlist: 'विशलिस्ट',
    help_support: 'मदत आणि समर्थन',
    app_theme_settings: 'अ‍ॅप थीम सेटिंग्ज',
    privacy_security: 'गोपनीयता आणि सुरक्षितता',
    saved_addresses: 'जतन केलेले पत्ते',
    payment_methods: 'पैसे भरण्याच्या पद्धती',
    edit_profile: 'प्रोफाइल संपादीत करा',
    notifications: 'सूचना',
    product_details: 'उत्पादन तपशील',
    quantity: 'प्रमाण:',
    product_overview: 'उत्पादन विहंगावलोकन',
    highlights_features: 'ठळक वैशिष्ट्ये',
    specifications: 'तपशील',
    seller_fulfillment: 'विक्रेते आणि पूर्तता',
    warranty_support: 'वॉरंटी आणि सपोर्ट',
    add_to_cart: 'कार्टमध्ये जोडा',
    in_cart: 'कार्टमध्ये आहे',
    order_now: 'आत्ताच ऑर्डर करा',
    apply_now: 'आत्ताच अर्ज करा',
    rent_now: 'भाड्याने घ्या',
    reserve_stay: 'स्टे बुक करा',
    book_ticket: 'तिकीट बुक करा',
    free_delivery_members: 'कनेक्ट सदस्यांसाठी विनामूल्य डिलिव्हरी',
    verified_partner: 'सत्यापित भागीदार',
    verified_vendor: 'सत्यापित विक्रेता',
    authorized_seller: 'अधिकृत विक्रेता',
    condition: 'स्थिती',
    brand_new: 'नवीन',
    information_unavailable: 'माहिती उपलब्ध नाही',
    genuine_brand_product: 'संपूर्ण विक्रेता वॉरंटीसह अस्सल ब्रँड उत्पादन.',
    track_live: 'लाईव्ह ट्रॅक करा',
    view_details: 'तपशील पहा',
    reorder: 'पुन्हा ऑर्डर करा',
    cancel_order: 'ऑर्डर रद्द करा',
    download_invoice: 'इनव्हॉइस डाउनलोड करा',
    tracking_unavailable: 'ट्रॅकिंग उपलब्ध नाही',
    all_status: 'सर्व स्थिती',
    active: 'सक्रिय',
    delivered_completed: 'पूर्ण झाले',
    bookings: 'बुकिंग्ज',
    total_orders: 'एकूण ऑर्डर्स',
    full_name: 'पूर्ण नाव',
    phone_number: 'फोन नंबर',
    email_address: 'ईमेल पत्ता',
    date_of_birth: 'जन्म तारीख',
    save_changes: 'बदल जतन करा',
    stay_details: 'स्टे तपशील',
    check_in: 'चेक-इन',
    check_out: 'चेक-आउट',
    guests_and_rooms: 'पाहुणे आणि खोल्या',
  },
  Bengali: {
    home: 'হোম',
    categories: 'বিভাগসমূহ',
    orders: 'অর্ডার',
    membership: 'মেম্বারশিপ',
    profile: 'প্রোফাইল',
    daily_needs: 'দৈনন্দিন প্রয়োজন',
    services: 'পরিষেবা',
    products: 'পণ্য',
    food: 'খাবার',
    stay: 'স্টে',
    travel: 'ভ্রমণ',
    jobs: 'চাকরি',
    all: 'সব',
    filter: 'ফিল্টার',
    items: 'আইটেম',
    add: '+ যোগ করুন',
    fruits_vegetables: 'ফল ও শাকসবজি',
    grocery_staples: 'মুদি ও খাদ্যশস্য',
    fresh_daily_needs_groceries: 'তাজা দৈনন্দিন প্রয়োজন ও মুদি',
    my_orders: 'আমার অর্ডার',
    my_bookings: 'আমার বুকিং',
    membership_card: 'মেম্বারশিপ কার্ড',
    my_profile: 'আমার প্রোফাইল',
    wallet_balance: 'ওয়ালেট ব্যালেন্স',
    app_preferences: 'অ্যাপ পছন্দসমূহ',
    language: 'ভাষা',
    location: 'অবস্থান',
    light: 'লাইট',
    dark: 'ডার্ক',
    system: 'সিস্টেম',
    logout: 'লগআউট',
    search_placeholder: 'পণ্য, খাবার, পরিষেবা খুঁজুন...',
    popular_near_you: 'আপনার কাছে জনপ্রিয়',
    continue_browsing: 'ব্রাউজিং চালিয়ে যান',
    picked_for_you: 'আপনার জন্য নির্বাচিত',
    view_all: 'সব দেখুন →',
    explore_all: 'সব এক্সপ্লোর করুন →',
    buy_now: 'এখনই কিনুন',
    book_now: 'এখনই বুক করুন',
    book_service: 'পরিষেবা বুক করুন',
    deliver_to: 'ডেলিভারি ঠিকানা',
    select_language: 'ভাষা নির্বাচন করুন',
    choose_language_desc: 'আপনার পছন্দের ভাষা নির্বাচন করুন।',
    connect_app: 'কানেক্ট অ্যাপ',
    sign_in: 'সাইন ইন',
    sign_in_register: 'সাইন ইন / রেজিস্টার',
    cart: 'কার্ট',
    my_cart: 'আমার কার্ট',
    clear_all: 'সব মুছে ফেলুন',
    your_cart_is_empty: 'আপনার কার্ট খালি',
    start_shopping_now: 'এখনই কেনাকাটা শুরু করুন →',
    items_total: 'মোট আইটেম',
    delivery_fee: 'ডেলিভারি ফি',
    free: 'বিনামূল্যে',
    grand_total: 'মোট পরিমাণ',
    proceed_to_checkout: 'চেকআউটে এগিয়ে যান',
    checkout: 'চেকআউট',
    pay_and_place_order: 'পেমেন্ট করুন এবং অর্ডার দিন',
    delivery_address: 'ডেলিভারি ঠিকানা',
    change_address: 'ঠিকানা পরিবর্তন করুন',
    add_new_address: '+ নতুন ঠিকানা যোগ করুন',
    order_summary: 'অর্ডার সারাংশ',
    payment_method: 'পেমেন্ট পদ্ধতি',
    cash_on_delivery: 'ক্যাশ অন ডেলিভারি',
    online_payment: 'অনলাইন পেমেন্ট',
    wishlist: 'উইশলিস্ট',
    help_support: 'সাহায্য ও সহায়তা',
    app_theme_settings: 'অ্যাপ থিম সেটিংস',
    privacy_security: 'গোপনীয়তা ও নিরাপত্তা',
    saved_addresses: 'সংরক্ষিত ঠিকানা',
    payment_methods: 'পেমেন্ট পদ্ধতি',
    edit_profile: 'প্রোফাইল সম্পাদনা',
    notifications: 'বিজ্ঞপ্তি',
    product_details: 'পণ্যের বিবরণ',
    quantity: 'পরিমাণ:',
    product_overview: 'পণ্য ওভারভিউ',
    highlights_features: 'প্রধান বৈশিষ্ট্য',
    specifications: 'স্পেসিফিকেশন',
    seller_fulfillment: 'বিক্রেতা এবং পূর্ণতা',
    warranty_support: 'ওয়ারেন্টি ও সাপোর্ট',
    add_to_cart: 'কার্টে যোগ করুন',
    in_cart: 'কার্টে আছে',
    order_now: 'এখনই অর্ডার করুন',
    apply_now: 'এখনই আবেদন করুন',
    rent_now: 'ভাড়া নিন',
    reserve_stay: 'স্টে বুক করুন',
    book_ticket: 'টিকিট বুক করুন',
    free_delivery_members: 'কানেক্ট সদস্যদের জন্য বিনামূল্যে ডেলিভারি',
    verified_partner: 'যাচাইকৃত অংশীদার',
    verified_vendor: 'যাচাইকৃত বিক্রেতা',
    authorized_seller: 'অনুমোদিত বিক্রেতা',
    condition: 'অবস্থা',
    brand_new: 'একদম নতুন',
    information_unavailable: 'তথ্য পাওয়া যায়নি',
    genuine_brand_product: 'সম্পূর্ণ বিক্রেতা ওয়ারেন্টি সহ খাঁটি ব্র্যান্ডের পণ্য।',
    track_live: 'লাইভ ট্র্যাক করুন',
    view_details: 'বিস্তারিত দেখুন',
    reorder: 'পুনরায় অর্ডার করুন',
    cancel_order: 'অর্ডার বাতিল করুন',
    download_invoice: 'ইনভয়েস ডাউনলোড করুন',
    tracking_unavailable: 'ট্র্যাকিং পাওয়া যাচ্ছে না',
    all_status: 'সমস্ত অবস্থা',
    active: 'সক্রিয়',
    delivered_completed: 'ডেলিভার করা হয়েছে',
    bookings: 'বুকিং',
    total_orders: 'মোট অর্ডার',
    full_name: 'পুরো নাম',
    phone_number: 'ফোন নম্বর',
    email_address: 'ইমেল ঠিকানা',
    date_of_birth: 'জন্ম তারিখ',
    save_changes: 'পরিবর্তনগুলি সংরক্ষণ করুন',
    stay_details: 'স্টে বিবরণ',
    check_in: 'চেক-ইন',
    check_out: 'চেক-আউট',
    guests_and_rooms: 'অতিথি এবং রুম',
  },
};

const LANG_CODE_MAP: Record<string, string> = {
  English: 'en',
  Hindi: 'hi',
  Kannada: 'kn',
  Tamil: 'ta',
  Telugu: 'te',
  Malayalam: 'ml',
  Marathi: 'mr',
  Bengali: 'bn',
};

// Persistent & in-memory API translation cache
const TRANSLATION_API_CACHE: Record<string, Record<string, string>> = {};
const pendingApiFetches = new Set<string>();

// Load cached API translations from AsyncStorage on launch
(async () => {
  try {
    const rawCache = await AsyncStorage.getItem('connect_app_api_translation_cache');
    if (rawCache) {
      const parsed = JSON.parse(rawCache);
      Object.assign(TRANSLATION_API_CACHE, parsed);
    }
  } catch (err) {
    console.warn('[TranslationAPI] Cache load error:', err);
  }
})();

function normalizeKey(str: string): string {
  if (!str) return '';
  return str
    .toLowerCase()
    .trim()
    .replace(/[&\/\\#,+()$~%.'":*?<>{}]/g, '')
    .replace(/\s+/g, '_');
}

/**
 * Online Translation API Fetcher.
 * Uses Google Translate API endpoint to dynamically translate any dynamic text, card titles,
 * popups, and error messages into the target language.
 */
export async function fetchOnlineTranslation(text: string, langName: string): Promise<string | null> {
  const langCode = LANG_CODE_MAP[langName];
  if (!langCode || langCode === 'en' || !text || !text.trim()) return null;

  // Don't re-fetch numbers, prices, or short IDs
  if (/^[\d\s₹$.,+%-]+$/.test(text) || text.length > 500) return null;

  if (TRANSLATION_API_CACHE[langName]?.[text]) {
    return TRANSLATION_API_CACHE[langName][text];
  }

  const cacheKey = `${langName}:::${text}`;
  if (pendingApiFetches.has(cacheKey)) return null;
  pendingApiFetches.add(cacheKey);

  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${langCode}&dt=t&q=${encodeURIComponent(text.trim())}`;
    const response = await fetch(url);
    const data = await response.json();
    if (Array.isArray(data) && Array.isArray(data[0])) {
      const translatedText = data[0].map((item: any) => item[0]).filter(Boolean).join('');
      if (translatedText && translatedText.trim()) {
        if (!TRANSLATION_API_CACHE[langName]) {
          TRANSLATION_API_CACHE[langName] = {};
        }
        TRANSLATION_API_CACHE[langName][text] = translatedText;

        // Persist to AsyncStorage asynchronously
        AsyncStorage.setItem('connect_app_api_translation_cache', JSON.stringify(TRANSLATION_API_CACHE)).catch(() => {});

        // Trigger store re-render to update UI with newly translated API response
        useLanguageStore.getState().triggerRefresh();
        return translatedText;
      }
    }
  } catch (err) {
    console.warn('[TranslationAPI] Network fetch notice:', err);
  } finally {
    pendingApiFetches.delete(cacheKey);
  }

  return null;
}

export function getTranslation(keyOrText: string, langName: string = 'English'): string {
  if (!keyOrText) return '';
  const normKey = normalizeKey(keyOrText);

  if (langName === 'English') {
    return TRANSLATIONS['English'][keyOrText] || TRANSLATIONS['English'][normKey] || keyOrText;
  }

  const langTable = TRANSLATIONS[langName] || TRANSLATIONS['English'];

  // 1. Exact key match in target language static dictionary
  if (langTable[keyOrText]) {
    return langTable[keyOrText];
  }
  // 2. Normalized key match in target language static dictionary
  if (langTable[normKey]) {
    return langTable[normKey];
  }
  // 3. API Translation Cache match
  if (TRANSLATION_API_CACHE[langName]?.[keyOrText]) {
    return TRANSLATION_API_CACHE[langName][keyOrText];
  }
  if (TRANSLATION_API_CACHE[langName]?.[normKey]) {
    return TRANSLATION_API_CACHE[langName][normKey];
  }

  // 4. Trigger background Translation API fetch for dynamic/unknown text
  if (typeof keyOrText === 'string' && keyOrText.trim().length > 1) {
    fetchOnlineTranslation(keyOrText, langName);
  }

  // 5. Temporary fallback while fetching
  if (TRANSLATIONS['English'][normKey]) {
    return TRANSLATIONS['English'][normKey];
  }
  if (TRANSLATIONS['English'][keyOrText]) {
    return TRANSLATIONS['English'][keyOrText];
  }

  return keyOrText;
}

interface LanguageState {
  currentLanguage: string;
  refreshKey: number;
  setLanguage: (langName: string) => void;
  triggerRefresh: () => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      currentLanguage: 'English',
      refreshKey: 0,
      setLanguage: (langName: string) => set({ currentLanguage: langName, refreshKey: get().refreshKey + 1 }),
      triggerRefresh: () => set({ refreshKey: get().refreshKey + 1 }),
      t: (key: string) => getTranslation(key, get().currentLanguage),
    }),
    {
      name: 'connect_app_language_storage',
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({ currentLanguage: state.currentLanguage }),
    }
  )
);

/**
 * Universal reactive Translation hook for React components.
 * Subscribes to `currentLanguage` & `refreshKey` so any language update or API translation re-renders immediately!
 */
export function useTranslation() {
  const currentLanguage = useLanguageStore((state) => state.currentLanguage);
  const refreshKey = useLanguageStore((state) => state.refreshKey);
  const setLanguage = useLanguageStore((state) => state.setLanguage);

  const t = (keyOrText: string) => getTranslation(keyOrText, currentLanguage);

  return { t, currentLanguage, setLanguage, refreshKey };
}

