export interface TravelRideItem {
  id: string;
  name: string;
  operator: string;
  type: 'Bus' | 'Cab' | 'Bike';
  subType: string;
  from: string;
  to: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewsCount: number;
  seatsLeft?: number;
  capacity?: string;
  boardingPoints: string[];
  droppingPoints: string[];
  amenities: string[];
  badge?: string;
  image: string;
  rawProduct?: any;
}

export const CURATED_TRAVEL_SERVICES: TravelRideItem[] = [
  // --- BUSES ---
  {
    id: 'bus_vrl_1',
    name: 'Multi-Axle Volvo AC Sleeper (2+1)',
    operator: 'VRL Travels',
    type: 'Bus',
    subType: 'AC Sleeper',
    from: 'Bangalore',
    to: 'Chennai',
    departureTime: '21:30',
    arrivalTime: '05:30',
    duration: '8h 00m',
    price: 950,
    originalPrice: 1200,
    rating: 4.8,
    reviewsCount: 1420,
    seatsLeft: 12,
    boardingPoints: ['Majestic (09:30 PM)', 'Madiwala (10:15 PM)', 'Electronic City (10:45 PM)'],
    droppingPoints: ['Sriperumbudur (04:30 AM)', 'Koyambedu (05:15 AM)', 'Guindy (05:30 AM)'],
    amenities: ['AC Sleeper', 'Live GPS', 'Charging Point', 'Blanket', 'Water Bottle'],
    badge: 'Top Rated Bus',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bus_ksrtc_2',
    name: 'Airavat Club Class - Volvo Multi-Axle',
    operator: 'KSRTC Airavat',
    type: 'Bus',
    subType: 'Semi-Sleeper AC',
    from: 'Bangalore',
    to: 'Chennai',
    departureTime: '22:15',
    arrivalTime: '06:00',
    duration: '7h 45m',
    price: 820,
    originalPrice: 950,
    rating: 4.7,
    reviewsCount: 980,
    seatsLeft: 8,
    boardingPoints: ['Kempegowda Bus Station (10:15 PM)', 'Shantinagar (10:45 PM)', 'Hosur (11:30 PM)'],
    droppingPoints: ['Poonamallee (05:15 AM)', 'Koyambedu CMBT (06:00 AM)'],
    amenities: ['Semi-Sleeper AC', 'Live Tracking', 'Emergency Button', 'CCTV'],
    badge: 'Government Certified',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bus_intrcity_3',
    name: 'SmartBus Luxury AC Sleeper (Washroom)',
    operator: 'IntrCity SmartBus',
    type: 'Bus',
    subType: 'AC Sleeper Washroom',
    from: 'Bangalore',
    to: 'Hyderabad',
    departureTime: '22:00',
    arrivalTime: '06:30',
    duration: '8h 30m',
    price: 1150,
    originalPrice: 1450,
    rating: 4.9,
    reviewsCount: 2240,
    seatsLeft: 6,
    boardingPoints: ['Anand Rao Circle (10:00 PM)', 'Hebbal (10:45 PM)', 'Yelahanka (11:15 PM)'],
    droppingPoints: ['Shamshabad (05:45 AM)', 'Gachibowli (06:15 AM)', 'Ameerpet (06:30 AM)'],
    amenities: ['Washroom Onboard', 'Smart Bus Lounge', 'Free Wi-Fi', 'Snack Box'],
    badge: 'Luxury Sleeper',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bus_orange_4',
    name: 'BharatBenz AC Seater Express',
    operator: 'Orange Tours & Travels',
    type: 'Bus',
    subType: 'AC Seater',
    from: 'Bangalore',
    to: 'Coimbatore',
    departureTime: '06:30',
    arrivalTime: '13:00',
    duration: '6h 30m',
    price: 650,
    originalPrice: 850,
    rating: 4.6,
    reviewsCount: 760,
    seatsLeft: 18,
    boardingPoints: ['Kalasipalyam (06:30 AM)', 'Silk Board (07:15 AM)', 'Electronic City (07:35 AM)'],
    droppingPoints: ['Salem Bypass (10:45 AM)', 'Gandhipuram Omni Bus Stand (01:00 PM)'],
    amenities: ['Comfort Recliner', 'AC', 'USB Charging', 'Reading Light'],
    badge: 'Day Express',
    image: 'https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bus_morningstar_5',
    name: 'Scania AC Multi-Axle Sleeper',
    operator: 'Morning Star Travels',
    type: 'Bus',
    subType: 'Multi-Axle Sleeper',
    from: 'Chennai',
    to: 'Bangalore',
    departureTime: '23:00',
    arrivalTime: '06:30',
    duration: '7h 30m',
    price: 890,
    originalPrice: 1100,
    rating: 4.8,
    reviewsCount: 890,
    seatsLeft: 14,
    boardingPoints: ['Koyambedu (11:00 PM)', 'Porur Toll (11:30 PM)', 'Sriperumbudur (11:55 PM)'],
    droppingPoints: ['Hosur (05:30 AM)', 'Electronic City (06:00 AM)', 'Madiwala (06:30 AM)'],
    amenities: ['AC Sleeper', 'Live GPS', 'Clean Linens', 'Luggage Tag'],
    badge: 'Super Fast',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bus_srs_6',
    name: 'AC Sleeper Coach Direct',
    operator: 'SRS Travels',
    type: 'Bus',
    subType: 'AC Sleeper',
    from: 'Bangalore',
    to: 'Goa',
    departureTime: '19:30',
    arrivalTime: '08:00',
    duration: '12h 30m',
    price: 1100,
    originalPrice: 1350,
    rating: 4.4,
    reviewsCount: 650,
    seatsLeft: 9,
    boardingPoints: ['Yesvantpur (07:30 PM)', 'Goraguntepalya (08:00 PM)', 'Tumkur Bypass (09:00 PM)'],
    droppingPoints: ['Margao (06:45 AM)', 'Panaji Kadamba Bus Terminus (07:30 AM)', 'Mapusa (08:00 AM)'],
    amenities: ['Double AC Sleeper', 'Blanket', 'Emergency Kit'],
    badge: 'Popular Route',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&auto=format&fit=crop&q=70',
  },

  // --- CABS ---
  {
    id: 'cab_prime_1',
    name: 'Prime Sedan (Swift Dzire / Toyota Etios)',
    operator: 'Connect Prime Cabs',
    type: 'Cab',
    subType: 'Sedan AC',
    from: 'Bangalore',
    to: 'Chennai',
    departureTime: 'Anytime / On-Demand',
    arrivalTime: '6h 00m Direct',
    duration: '6 hrs',
    price: 3499,
    originalPrice: 4200,
    rating: 4.9,
    reviewsCount: 3100,
    capacity: '4 Passenger Seats + 3 Bags',
    boardingPoints: ['Doorstep Pickup anywhere in Bangalore'],
    droppingPoints: ['Doorstep Drop anywhere in Chennai'],
    amenities: ['AC Sedan', 'Clean & Sanitized', 'Top Chauffeur', 'Toll Paid Option', 'Live GPS'],
    badge: 'Fastest Door-to-Door',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'cab_suv_2',
    name: 'Executive SUV (Toyota Innova Crysta)',
    operator: 'Connect Outstation Fleet',
    type: 'Cab',
    subType: 'SUV AC',
    from: 'Bangalore',
    to: 'Chennai',
    departureTime: 'Anytime / Flexible',
    arrivalTime: '5h 45m Direct',
    duration: '5h 45m',
    price: 5499,
    originalPrice: 6500,
    rating: 4.9,
    reviewsCount: 1800,
    capacity: '6-7 Passenger Seats + 5 Bags',
    boardingPoints: ['Doorstep Pickup anywhere in Bangalore'],
    droppingPoints: ['Doorstep Drop anywhere in Chennai'],
    amenities: ['Captain Recliner Seats', 'Dual Zone AC', 'Extra Luggage Carrier', 'Verified Driver'],
    badge: 'Family & Luxury',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'cab_prime_3',
    name: 'Prime Sedan Outstation One-Way',
    operator: 'Connect Prime Cabs',
    type: 'Cab',
    subType: 'Sedan AC',
    from: 'Bangalore',
    to: 'Coimbatore',
    departureTime: 'Anytime / Scheduled',
    arrivalTime: '6h 30m Direct',
    duration: '6h 30m',
    price: 4299,
    originalPrice: 5100,
    rating: 4.8,
    reviewsCount: 890,
    capacity: '4 Seats + Boot Space',
    boardingPoints: ['Doorstep Pickup anywhere in Bangalore'],
    droppingPoints: ['Doorstep Drop anywhere in Coimbatore'],
    amenities: ['AC Sedan', 'Zero Cancellation Fee', 'Realtime Tracking', 'Bottle & Tissues'],
    badge: 'Best Value Cab',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'cab_mini_4',
    name: 'City & Outstation Mini (WagonR / Tiago)',
    operator: 'Connect Quick Cabs',
    type: 'Cab',
    subType: 'Hatchback AC',
    from: 'Bangalore',
    to: 'Mysore',
    departureTime: 'Anytime / Instant 15 mins',
    arrivalTime: '3h 00m Direct',
    duration: '3 hrs',
    price: 1899,
    originalPrice: 2200,
    rating: 4.7,
    reviewsCount: 1450,
    capacity: '4 Seats',
    boardingPoints: ['Doorstep Pickup in Bangalore'],
    droppingPoints: ['Doorstep Drop in Mysore'],
    amenities: ['AC Mini', 'Budget Friendly', 'Toll Highway Tag'],
    badge: 'Economical',
    image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'cab_prime_5',
    name: 'Prime Sedan Express Intercity',
    operator: 'Connect Prime Cabs',
    type: 'Cab',
    subType: 'Sedan AC',
    from: 'Chennai',
    to: 'Bangalore',
    departureTime: 'Anytime / Flexible',
    arrivalTime: '6h 00m Direct',
    duration: '6 hrs',
    price: 3499,
    originalPrice: 4200,
    rating: 4.9,
    reviewsCount: 1220,
    capacity: '4 Seats + 3 Bags',
    boardingPoints: ['Doorstep Pickup in Chennai'],
    droppingPoints: ['Doorstep Drop in Bangalore'],
    amenities: ['AC Sedan', 'Verified Driver', 'Water Bottle', 'Live GPS'],
    badge: 'Instant Pickup',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&auto=format&fit=crop&q=70',
  },

  // --- BIKES ---
  {
    id: 'bike_re_1',
    name: 'Royal Enfield Classic 350 - Touring Edition',
    operator: 'Connect Motor Rental Hub',
    type: 'Bike',
    subType: 'Cruiser 350cc',
    from: 'Bangalore',
    to: 'Goa',
    departureTime: 'Pickup from Hub (8 AM - 10 PM)',
    arrivalTime: 'Self-Drive Rental',
    duration: 'Per Day / Trip',
    price: 899,
    originalPrice: 1100,
    rating: 4.8,
    reviewsCount: 780,
    capacity: '2 Riders + Luggage Rack',
    boardingPoints: ['Koramangala Hub', 'Indiranagar Hub', 'Electronic City Hub'],
    droppingPoints: ['Panaji Drop Hub', 'Bangalore Return Hub'],
    amenities: ['350cc Dual ABS', '2 Certified Helmets', 'Mobile Phone Mount', 'Luggage Carrier', 'Zero Deposit KYC'],
    badge: 'Touring Beast',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bike_activa_2',
    name: 'Honda Activa 6G - Fuel Efficient Explorer',
    operator: 'Connect City Rides',
    type: 'Bike',
    subType: 'Scooter 110cc',
    from: 'Bangalore',
    to: 'Mysore',
    departureTime: 'Instant Pickup',
    arrivalTime: 'Self-Drive Rental',
    duration: 'Per Day',
    price: 399,
    originalPrice: 550,
    rating: 4.7,
    reviewsCount: 1650,
    capacity: '2 Riders',
    boardingPoints: ['Majestic Hub', 'BTM Layout Hub', 'Whitefield Hub'],
    droppingPoints: ['Mysore City Hub', 'Bangalore Hub Return'],
    amenities: ['110cc Automatic', '50+ KMPL Mileage', 'Free Helmet', 'Tubeless Tyres'],
    badge: 'Easy & Light',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bike_ktm_3',
    name: 'KTM Duke 250 - High Performance Touring',
    operator: 'Connect Motor Rental Hub',
    type: 'Bike',
    subType: 'Sports 250cc',
    from: 'Bangalore',
    to: 'Coimbatore',
    departureTime: 'Hub Pickup',
    arrivalTime: 'Self-Drive',
    duration: 'Per Day',
    price: 1199,
    originalPrice: 1500,
    rating: 4.9,
    reviewsCount: 540,
    capacity: '1-2 Riders',
    boardingPoints: ['Koramangala Hub', 'Rajajinagar Hub'],
    droppingPoints: ['Coimbatore Hub', 'Bangalore Hub Return'],
    amenities: ['250cc Liquid Cooled', 'Slipper Clutch', 'Premium Riding Gear Available', 'GPS Mount'],
    badge: 'Sports Cruiser',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=400&auto=format&fit=crop&q=70',
  },
  {
    id: 'bike_hunter_4',
    name: 'Royal Enfield Hunter 350 - Urban & Highway',
    operator: 'Connect Motor Rental Hub',
    type: 'Bike',
    subType: 'Roadster 350cc',
    from: 'Chennai',
    to: 'Bangalore',
    departureTime: 'Hub Pickup',
    arrivalTime: 'Self-Drive',
    duration: 'Per Day',
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviewsCount: 620,
    capacity: '2 Riders',
    boardingPoints: ['T Nagar Hub', 'Velachery Hub', 'Tambaram Hub'],
    droppingPoints: ['Bangalore Hub', 'Chennai Hub'],
    amenities: ['350cc J-Series Engine', '2 Free Helmets', 'Puncture Kit Included'],
    badge: 'Agile & Smooth',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=400&auto=format&fit=crop&q=70',
  },
];
