const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  quantity: { type: Number, default: 1 },
  price: { type: Number, required: true },
  variant: { type: String },
}, { _id: false });

const orderSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true },
  order_number: { type: String, required: true, index: true },
  vendor_id: { type: String, default: 'v1' },
  vendor_name: { type: String, default: 'Connect Official Store' },
  category: { type: String, default: 'Products' },
  order_type: { type: String, enum: ['order', 'booking'], default: 'order' },
  customer_name: { type: String, default: 'Uma' },
  customer_phone: { type: String, default: '+91 98765 43210' },
  customer_address: { type: String, default: 'Flat 402, Prestige Tower, Indiranagar, Bangalore' },
  customer_latitude: { type: Number, default: 12.9716 },
  customer_longitude: { type: Number, default: 77.6412 },
  product_details: { type: String, default: '' },
  brand_or_seller: { type: String, default: 'Connect Verified' },
  image: { type: String, default: '' },
  items: [orderItemSchema],
  item_count: { type: Number, default: 1 },
  amount: { type: Number, required: true },
  status: {
    type: String,
    enum: [
      'Order Received',
      'Confirmed',
      'Preparing',
      'Assigned To Delivery Partner',
      'Delivery Partner Accepted',
      'Ready For Pickup',
      'Picked Up',
      'Out For Delivery',
      'Near Customer',
      'Delivered',
      'Completed',
      'Cancelled'
    ],
    default: 'Order Received',
    index: true,
  },
  expected_delivery: { type: String },
  delivered_at: { type: String },
  payment_method: { type: String, default: 'Paid via UPI' },
  payment_status: { type: String, default: 'Paid' },
  delivery_fee: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  tax: { type: Number, default: 0 },
  rating: { type: Number },
  review_note: { type: String },
  provider_name: { type: String },
  appointment_slot: { type: String },
  operator_name: { type: String },
  route: { type: String },
  travel_date: { type: String },
  passenger_count: { type: Number },
  hotel_name: { type: String },
  check_in: { type: String },
  check_out: { type: String },
  guests_count: { type: String },
  room_type: { type: String },
}, { timestamps: true });

module.exports = mongoose.model('Order', orderSchema);
